# Default values for demo-app.
replicaCount: 2
revisionHistoryLimit: 5
envName: prod
image:
  repository: docker.io/limnick/gcloud_storage_list_example
  tag: 0.2.2
  pullPolicy: Always
gcloudKeySecretName: demo-app-gcs-keys
gcloudKeyName: storage-reader-sharktopus.json
gcloudBucketName: toy-bucket
service:
  name: demo-app
  type: LoadBalancer
  externalPort: 80
  internalPort: 8888
resources:
  requests:
    cpu: 10m
    memory: 128Mi
